In [1]:
import pandas as pd
import numpy as np

In [4]:
labels = ['a','b','c']
list1 = [10,20,30]
a=np.array([10,20,20])
d = { 'a' : 10, 'b':20,'c':30}

In [6]:
pd.Series(data = list1)

0    10
1    20
2    30
dtype: int64

In [7]:
pd.Series(data = list1,index = labels)

a    10
b    20
c    30
dtype: int64

In [8]:
pd.Series(list1,labels)

a    10
b    20
c    30
dtype: int64

In [9]:
pd.Series(a)

0    10
1    20
2    20
dtype: int64

In [10]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [11]:
pd.Series(a,labels)

a    10
b    20
c    20
dtype: int64

In [12]:
ser1 = pd.Series([10,20,30,40], index = ['apple','mango','grapes','cherry']) 
ser2 = pd.Series([10,30,40,50], index = ['apple','grapes','cherry','kiwi'])
ser1 + ser2

apple     20.0
cherry    80.0
grapes    60.0
kiwi       NaN
mango      NaN
dtype: float64

In [13]:
ser1["mango"]

np.int64(20)

In [14]:
from numpy.random import randn
np.random.seed(101)

In [17]:
df = pd.DataFrame(randn(5,4),index = 'A B C D E'.split(),columns = 'W X Y Z'.split())
df

          W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [18]:
df['Z']

A    0.000366
B    0.649826
C   -0.346419
D    1.024810
E    0.610478
Name: Z, dtype: float64

In [20]:
df[['Z','X']]

          Z         X
A  0.000366  0.196800
B  0.649826 -0.156598
C -0.346419 -0.610259
D  1.024810 -0.479448
E  0.610478  1.862864

In [21]:
df['new'] = df ['Z'] + df ['W']
df

          W         X         Y         Z       new
A -0.993263  0.196800 -1.136645  0.000366 -0.992897
B  1.025984 -0.156598 -0.031579  0.649826  1.675810
C  2.154846 -0.610259 -0.755325 -0.346419  1.808428
D  0.147027 -0.479448  0.558769  1.024810  1.171837
E -0.925874  1.862864 -1.133817  0.610478 -0.315396

In [22]:
df.drop(columns = 'new' , axis = 1 )

          W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478